# Generated by Django 4.2.3 on 2023-07-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(default='palce_id', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='point_title',
            field=models.CharField(default='point_title', max_length=100, verbose_name='Название метки на карте'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
