# Generated by Django 4.2.3 on 2023-07-30 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_place_id_place_point_title_alter_place_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.place'),
        ),
    ]
