# Generated by Django 4.2.3 on 2023-07-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_image_img_number_alter_image_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img_number',
        ),
        migrations.AddField(
            model_name='image',
            name='img_position',
            field=models.IntegerField(default=1, verbose_name='Позиция'),
            preserve_default=False,
        ),
    ]
